@HostAddressRoot = https://localhost:7293

GET {{HostAddressRoot}}/api/destinations?searchFor=a
Accept: application/json

###

GET {{HostAddressRoot}}/api/itineraries?searchFor=a
Accept: application/json

###

GET {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json

###

GET {{HostAddressRoot}}/api/itineraries/1111/stops
Accept: application/json

###

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-Type: application/json

{
  "name": "a stop for testing",
  "imageUri": "https://localhost:7120/images/stopfortesting.jpg"
}

###

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-Type: application/json

{
  "imageUri": "https://localhost:7120/images/stopfortesting.jpg"
}

###

POST {{HostAddressRoot}}/api/itineraries/1/stops
Accept: application/json
Content-Type: application/json

{
  "imageUri": "not valid"
}

###

PUT {{HostAddressRoot}}/api/itineraries/1/stops/1
Accept: application/json
Content-Type: application/json

{
  "name": "An updated name"
}

###

GET {{HostAddressRoot}}/api/itineraries?searchFor=a
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkEiLCJzdWIiOiJBIiwianRpIjoiY2I4ZmVlYmQiLCJhdWQiOiJ0cmF2ZWxpbnNwaXJhdGlvbi1hcGkiLCJuYmYiOjE3NzE2Njk2MjAsImV4cCI6MTc3OTM1OTIyMCwiaWF0IjoxNzcxNjY5NjIxLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.xYW1MaaUf9rr8xj59m9EQpC81268MF-GGOBsT7zSUAY